### ISSUE TITLE
Individual counseling view

### ISSUE THREAD

**Issue by choipd** [dasomx/mind-center#5]
# **Individual counseling (List)**

# **Description**

- 내담자의 저장된 상담정보를 리스트로 표시하는 화면
- 먼저 상단에 표시되는 항목은 General Counseling registration에서 입력된 자료 중 다음과 같은 항목을 표시한다.
    - Code
    - Name
    - Gender
    - Disaster Name
    - Disaster type
    - Disaster Victim Type
    - Job
    - Case manager
    - Referral
- 개별상담의 리스트에 다음과 같은 항목을 표시한다. (변경함 v20240518)
    - Counseling date
    - Start Time
    - End Time
    - Counseling topic
    - Counselor

# **Individual counseling (View)**

# **Description**

- 리스트로 표시된 개별상담 정보 중 선택된 상담정보의 상세 내용을 표시하는 화면
- 표시되는 항목은 다음과 같다.
    - Counselor
    - Counseling type
    - Counseling time
        - Start time
        - End time
        - Time taken
    - Name (Disaster Victim)
    - Disaster Name
    - Information Provider
        - Name
        - Relationship with the Victim
        - Mobile
        - Home
        - Address
    - Disaster type
    - Disaster Victim Type
    - Emergency Intervention
    - Counseling topic
    - Counseling Detail
    - Contents of Psychological Aid
    - Profile : 5개의 영역에 대한 평가를 표시한다. 예) [Psychological 5] [Physical 3] [Social 1] [Educational 9] [Financial 5] [Spiritual 3] è Total : 00 / Average : 00

**Comment by wisesam** [comment]
제가 오늘 한 번 해보겠습니다.

**Comment by choipd** [comment]
화이팅입니다!
