### ISSUE TITLE
Link/Refer request regist

### ISSUE THREAD

**Issue by choipd** [dasomx/mind-center#6]
# **Link/Refer request (Register)**

# **Description**

- 내담자를 다른 기관에 연계 의뢰하기 위한 화면
- **<아래는 검색기능>**
- 가장 먼저 Name 또는 Mobile로 입력하면 해당하는 사람의 리스트가 표시된다.
    - 표시되는 항목으로는 다음과 같고 Name을 클릭하면 하단에 내담자의 상담정보를 입력하도록 한다.
        - Name
        - Disaster Type
        - Mobile
        - DoB
        - Code
- 표시되는 내담자의 기본정보는 다음과 같다.
    - Code
    - Gender
    - Disaster Name
    - Disaster type
    - Disaster Victim Type
    - Job
    - Case manager
    - Referral
- 내담자의 연계의뢰 입력항목은 다음과 같다
    - Category : 다음 항목중 하나만 선택한다.
        - Killed
        - Injured
        - Church burnt
        - House burnt
        - Looted
        - Other
    - Processing date : 연계 날짜를 입력한다.
    - Organization Group : 연계기관의 그룹을 입력한다.
        - Career Counselor
        - Psychiatrist
        - Vocational Trainer
        - Lawyer
        - Others
    - Organization Name: 연계기관 이름을 입력한다.
    - Referral Name : 연계의뢰자 이름을 입력한다.
    - Receptionist : 접수자 이름을 입력한다.
    - Reason : 정확한 사유에 대해 장문의 텍스트를 입력할 수 있고, 사진도 첨부하여 내용에 함께 표시한다.

**Comment by wisesam** [comment]
제가 Link/Refer를 해보겠습니다.

**Comment by choipd** [comment]
구현이 되어 종료합니다.
