### ISSUE TITLE
General의 Status가 자동으로 업데이트 되도록 해주세요

### ISSUE THREAD

**Issue by pak-park** [dasomx/mind-center#96]
General의 Status가 자동으로 업데이트 되도록 해주세요

* Counseling이 진행되고 있다면 General의 Status가 자동으로 “In Progress”로 되도록
* Ending이 되면 자동으로 “Completed”가 되도록
* 현재상태라면 Cancelled, Pending, Deleted에 대해서는 내부적인 프로세스가 없습니다. 이 세가지 상태를 없애도 문제가 없을까요? 의견을 구합니다.
   i.	Pending에 대해서는 아이디어가 없습니다. 어떻게하면 좋을까요?
   ii.	Deleted는 General 데이터를 만든 후 상담이 진행 중 개인정보가 삭제될떄인가요?

**Comment by wisesam** [comment]
- 네 자동으로 바뀌는 것 필요하겠습니다. (예상작업시간: 2h)
- Deleted는 필요없는 듯
- Pending의 경우 메모에다가 이유 추가하면 어떨지 (어떤 이유로 인해 치료가 중단된 경우)

**Comment by choipd** [comment]
- Cancelled는 상담이 취소되는 경우가 있을 거 같아서요.
- Pending은 잠깐 멈췄다가 다시 재개될 수 있는 상태라고 보입니다.
- Deleted는 삭제할 경우에 모든 기록을 바로 삭제하지 않고 일정 시간이 지나면 완전히 삭제하는 용도로 활용하면 어떨까요?

**Comment by pak-park** [comment]
> * Cancelled는 상담이 취소되는 경우가 있을 거 같아서요.
> * Pending은 잠깐 멈췄다가 다시 재개될 수 있는 상태라고 보입니다.
> * Deleted는 삭제할 경우에 모든 기록을 바로 삭제하지 않고 일정 시간이 지나면 완전히 삭제하는 용도로 활용하면 어떨까요?

Cancelled과 Pending은 이해가 되었습니다. 
그렇다면 Cancelled과 Pending 상태에서 상담이 다시 재개되면 상태가 자동으로 변경되는거겠죠?
